#!/bin/sh

# Localisation
if [ -f /usr/bin/gettext.sh ]; then
	. /usr/bin/gettext.sh || exit 1
else
	exit 1
fi

export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=sidux-vdr


# determine system status
SSFTSH="$(which ssft.sh)"	|| SSFTSH="/usr/bin/ssft.sh"

# initialize ssft
. "$SSFTSH"
[ -n "$SSFT_FRONTEND" ] ||  SSFT_FRONTEND="$(ssft_choose_frontend)"


VDRMANUAL="www.linuxtv.org/vdrwiki/index.php/VDR_User%27s_Manual"
[ $(echo $LANG|cut -c1-2) = de ] && VDRMANUAL="www.vdr-wiki.de/wiki/index.php/Benutzerhandbuch"


ssft_select_single  $(gettext "VDR Menu")" $(gettext "Start VDR Programs\n\nMake your choice:")" \
	"1) $(gettext "sx(fb)fe-player (TV-Picture)")" \
	"4) $(gettext "Change VDR IP-Adress for Xine-Player")" \
	"5) $(gettext "VDR-Update")" \
	"6) $(gettext "Xine-Autostart (TV-Picture)")" \
	"7) $(gettext "vdrlive (Webfrontend)")" \
	"8) $(gettext "VDR User Manual")" \
	"9)  $(gettext "Show xine Keyboardlayout")" \
	"10) $(gettext "Exit")" \
      || exit

answer=$(echo "$SSFT_RESULT" | cut -d\) -f1)

case $answer in
	"1")
    		/usr/sbin/vdr-xine sxfe && exit
		;;
	"4")
    		/usr/sbin/vdr-ip
		;;
	"5")
		su-to-root -X -c "/usr/bin/x-terminal-emulator -e /usr/sbin/vdr-update"
		;;
	"6")
		x-terminal-emulator -e /usr/sbin/vdr-xine-autorun
		;;
	"7")
		/usr/sbin/vdr-live
		;;
	"8")
		x-www-browser "http://${VDRMANUAL}" &
		;;
	"9")
		x-terminal-emulator -C -e /usr/sbin/vdr-xine-tasteninfo
		;;
	"10")
		exit
		;;
	*)
		break
		;;
esac

exec /usr/sbin/vdr-start-menu

