#!/bin/sh

# Localisation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=kanotix-vdr

DIALOG="dialog"
[ -n "$DISPLAY" ] && [ -x /usr/bin/Xdialog ] && DIALOG="Xdialog"

VDRMANUAL="www.linuxtv.org/vdrwiki/index.php/VDR_User%27s_Manual"
[ $(echo $LANGUAGE|cut -c1-2) = de ] && VDRMANUAL="www.vdr-wiki.de/wiki/index.php/Benutzerhandbuch"

tempfile=`tempfile 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15
$DIALOG --clear --title $"VDR Menu" \
        --menu $"Start VDR Programs\n\nMake your choice:" 30 62 20 \
        ""  "~~~~~~~~ "$"xine"" ~~~~~~~~ " \
        "1)"  $"sx(fb)fe-player (TV-Picture)" \
        "2)"  $"xine-player (TV-Picture)" \
        "3)"  $"Get xine Keyboardlayout for VDR" \
        "4)"  $"Change VDR IP-Adress for Xine-Player" \
        ""  "~~~~~~~~ "$"Miscellaneous"" ~~~~~~~~ " \
        "5)"  $"VDR-Update" \
        "6)"  $"Xine-Autostart (TV-Picture)" \
        "7)"  $"vdradmin (Webfrontend)" \
        "8)"  $"Kanotix-VDR config" \
        "9)"  $"VDR User Manual" \
        "10)"  $"Show xine Keyboardlayout" \
        "11)"  $"Exit" \
	2> $tempfile
answer="$?"
[ "$answer" = 1 ] && exit 1
answer=`cat $tempfile`
rm -f "$tempfile"


case $answer in
    "1)") /usr/sbin/vdr-xine sxfe && exit;;
    "2)") /usr/sbin/vdr-xine xine && exit;;
    "3)") rxvt -C -e /usr/sbin/vdr-xine-keymap;;
    "4)") /usr/sbin/vdr-ip;;
    "5)") kanotix-su rxvt -C -e /usr/sbin/vdr-update;;
    "6)") rxvt -C -e /usr/sbin/vdr-xine-autorun;;
    "7)") /usr/sbin/vdr-vdradmin;;
    "8)") /usr/sbin/vdr-config;;
    "9)") x-www-browser "http://${VDRMANUAL}" &;;
    "10)") rxvt -C -e /usr/sbin/vdr-xine-tasteninfo;;
    "11)") exit;;
    *)  break;;
esac

exec /usr/sbin/vdr-start-menu

