#!/bin/sh

# start vdr-gui if available
[ -x "/usr/bin/vdr-gui" ] && exec vdr-gui && exit 0

# Localisation
if [ -f /usr/bin/gettext.sh ]; then
	. /usr/bin/gettext.sh || exit 1
else
	exit 1
fi

export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=sidux-vdr


# determine system status
SSFTSH="$(which ssft.sh)"	|| SSFTSH="/usr/bin/ssft.sh"

# initialize ssft
#[ -n "$DISPLAY" ] && [ -x /usr/bin/kdialog ] && SSFT_FRONTEND="kdialog"
. "$SSFTSH"
[ -n "$SSFT_FRONTEND" ] ||  SSFT_FRONTEND="$(ssft_choose_frontend)"



VDRMANUAL="www.linuxtv.org/vdrwiki/index.php/VDR_User%27s_Manual"
[ $(echo $LANG|cut -c1-2) = de ] && VDRMANUAL="www.vdr-wiki.de/wiki/index.php/Benutzerhandbuch"

IP=`head -1 "$HOME/vdrip.conf" 2>/dev/null`
[ "$IP" = "" ] && IP="localhost"


ssft_select_single  $(gettext "VDR Menu")" $(gettext "Start VDR Programs\n\nMake your choice:")" \
	"1) $(gettext "sx(fb)fe-player (TV-Picture)")" \
	"4) $(gettext "Change VDR IP-Adress for Xine-Player")" \
	"5) $(gettext "Start VDR")" \
	"6) $(gettext "Stop VDR")" \
	"7) $(gettext "Change VDR Channelslist")" \
	"8) $(gettext "Allow client connect (insert IP from client)")" \
	"9) $(gettext "VDR-Channelscan Analog-Tuner Typ PVR")" \
	"10) $(gettext "Choose VDR-Harddiskpartition for recordings (Linux/FAT)")" \
	"11) $(gettext "VDR-Update")" \
	"12) $(gettext "VDR-Autostart")" \
	"13) $(gettext "Xine-Autostart (TV-Picture)")" \
	"14) $(gettext "vdradmin (Webfrontend)")" \
	"15) $(gettext "VDR User Manual")" \
	"16) $(gettext "Show xine Keyboardlayout")" \
	"17) $(gettext "Exit")" \
      || exit

answer=$(echo "$SSFT_RESULT" | cut -d\) -f1)

case $answer in
	"1") /usr/sbin/vdr-xine sxfe && exit;;
	"4") /usr/sbin/vdr-ip;;
	"5") su-me x-terminal-emulator -e /usr/sbin/vdr-start;;
	"6") su-me x-terminal-emulator -e /usr/sbin/vdr-stop;;
	"7") su-me /usr/sbin/vdr-channelswitch;;
	"8") su-me kwrite /etc/vdr/plugins/streamdevhosts.conf /etc/vdr/svdrphosts.conf;;
	"9") su-me x-terminal-emulator -e /usr/sbin/vdr-w_pvrscan pvrinput;;
	"10") su-me x-terminal-emulator -e /usr/sbin/vdr-videodir;;
	"11") su-me x-terminal-emulator -e /usr/sbin/vdr-update;;
	"12") su-me x-terminal-emulator -e /usr/sbin/vdr-autorun;;
	"13") x-terminal-emulator -e /usr/sbin/vdr-xine-autorun;;
	"14") /usr/sbin/vdr-vdradmin;;
	"15") x-www-browser "http://${VDRMANUAL}" &;;
	"16") x-terminal-emulator -e /usr/sbin/vdr-xine-tasteninfo;;
	"17") exit;;
	*)  break;;
esac

exec /usr/sbin/vdr-start-menu
