#!/bin/sh

# Localisation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=kanotix-vdr

DIALOG=Xdialog

VDRMANUAL="www.linuxtv.org/vdrwiki/index.php/VDR_User%27s_Manual"
[ $(echo $LANGUAGE|cut -c1-2) = de ] && VDRMANUAL="www.vdr-wiki.de/wiki/index.php/Benutzerhandbuch"

#DIALOG=dialog
IP=`head -1 "$HOME/vdrip.conf" 2>/dev/null`
[ "$IP" = "" ] && IP="localhost"

tempfile=`tempfile 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15
$DIALOG --clear --title $"VDR Menu" \
        --menu $"Start VDR Programs\n\nMake your choice:" 35 65 2 \
        ""  "~~~~~~~~ "$"xine"" ~~~~~~~~ " \
        "1)"  $"xine-player (TV-Picture)" \
        "2)"  $"Get xine Keyboardlayout for VDR" \
        "3)"  $"Show xine Keyboardlayout" \
        "4)"  $"Change VDR IP-Adress for Xine-Player" \
        ""  "~~~~~~~~ "$"VDR"" ~~~~~~~~ " \
        "5)"  $"Start VDR" \
        "6)"  $"Stop VDR" \
        "7)"  $"Change VDR Channelslist" \
        "8)"  $"Allow client connect (insert IP from client)" \
        "9)"  $"VDR-Channelscan Analog-Tuner Typ PVR" \
        "10)"  $"Choose VDR-Harddiskpartition for recordings (Linux/FAT)" \
        ""  "~~~~~~~~ "$"Miscellaneous"" ~~~~~~~~ " \
        "11)"  $"VDR-Update" \
        "12)"  $"VDR-Autostart" \
        "13)"  $"Xine-Autostart (TV-Picture)" \
        "14)"  $"vdradmin (Webfrontend)" \
        "15)"  $"Kanotix-VDR config" \
        "16)"  $"VDR User Manual" \
        "17)"  $"Exit" \
	2> $tempfile
answer="$?"
[ "$answer" = 1 ] && exit 1
answer=`cat $tempfile`
rm -f "$tempfile"


case $answer in
    "1)") /usr/sbin/vdr-xine && exit;;
    "2)") rxvt -C -e /usr/sbin/vdr-xine-keymap;;
    "3)") rxvt -C -e /usr/sbin/vdr-xine-tasteninfo;;
    "4)") /usr/sbin/vdr-ip;;
    "5)") kanotix-su rxvt -C -e /usr/sbin/vdr-start;;
    "6)") kanotix-su rxvt -C -e /usr/sbin/vdr-stop;;
    "7)") kanotix-su /usr/sbin/vdr-channelswitch;;
    "8)") kanotix-su kwrite /etc/vdr/plugins/streamdevhosts.conf /etc/vdr/svdrphosts.conf;;
    "9)") kanotix-su rxvt -C -e /usr/sbin/vdr-w_pvrscan pvrinput;;
    "10)") kanotix-su rxvt -C -e /usr/sbin/vdr-videodir;;
    "11)") kanotix-su rxvt -C -e /usr/sbin/vdr-update;;
    "12)") kanotix-su rxvt -C -e /usr/sbin/vdr-autorun;;
    "13)") rxvt -C -e /usr/sbin/vdr-xine-autorun;;
    "14)") /usr/sbin/vdr-vdradmin;;
    "15)") /usr/sbin/vdr-config;;
    "16)") x-www-browser "http://${VDRMANUAL}" &;;
    "17)") exit;;
    *)  break;;
esac

exec /usr/sbin/vdr-start-menu
