#!/bin/sh
set -e

# Create conffiles for vdr that do not exist yet
CONFFILES="setup.conf remote.conf remote.KBD.conf remote.XKeySym.conf"

case "$1" in
    configure)
        for CONF in $CONFFILES
        do
            if [ ! -e "/var/lib/vdr/$CONF" ] && [ -f "/var/lib/vdr/aptosid-vdr/$CONF" ]; then
                cp -f "/var/lib/vdr/aptosid-vdr/$CONF" "/var/lib/vdr/$CONF"
            fi
        done
        ;;
esac

#DEBHELPER#

