#!/bin/sh

. ssft.sh || exit 1

# Localisation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=aptosid-vdr

PART=`fdisk -l | grep -e "^/dev/" | grep -e "Linux" | grep -v "Swap" | cut -c6-12,57-66 | awk -F' ' '{print $1"_"$2}' && \
      fdisk -l | grep -e "^/dev/" | grep -e "FAT" | cut -c6-12,60-66 | awk -F' ' '{print $1"_"$2}' `


SSFT_FRONTEND="dialog"
[ -n "$DISPLAY" ] && SSFT_FRONTEND="zenity"

for index in $PART; do
	z=`expr $z + 1`
	line=`echo $index | tr ',' ' '`
	partlist="$partlist $line"
done


if ssft_select_single "Videodir" $"Choose partition" $partlist; then
  VIDEO_PART=$(echo "$SSFT_RESULT" | cut -d_ -f1)
else
  exit 0
fi

gemountet=`mount | grep /dev/$VIDEO_PART | wc -l`


if [ "$gemountet" = "0" ]; then
	mount "/dev/$VIDEO_PART" "/media/$VIDEO_PART"
fi

if [ ! -d  "/media/$VIDEO_PART" ]; then
	echo $"Creating /media/$VIDEO_PART"
	mkdir "/media/$VIDEO_PART"
	chmod 755 "/media/$VIDEO_PART"
fi

VIDEO_DIR="/media/$VIDEO_PART/video.00"


if [ ! -d  "$VIDEO_DIR" ]; then
	echo $"Creating $VIDEO_DIR"
	mkdir "$VIDEO_DIR"
fi


# Jetzt einfach das VIDEO Verzeichnis des VDR's ändern (wird in /etc/default/vdr gesetzt)
VIDEO_ORG=`grep "VIDEO_DIR=" /etc/default/vdr | cut -d'"' -f2 `

if [ "$VIDEO_ORG" = "" ]; then
	echo >> /etc/default/vdr && echo "VIDEO_DIR=\"$VIDEO_DIR\"" >> /etc/default/vdr
else
	perl -pi -e "s@$VIDEO_ORG@$VIDEO_DIR@g" /etc/default/vdr
fi

rm -f /var/lib/video && ln -s $VIDEO_DIR /var/lib/video
chown -R vdr:vdr $VIDEO_DIR /var/lib/video

if [ "$DIALOG" = "dialog" ]; then
	vdr-start
else
	x-terminal-emulator -e vdr-start
fi

ssft_display_message "Info" $"Your new video directory: $VIDEO_DIR"
