#!/bin/sh

# global configuration file - see vdr-config for more info
CONFIGFILE="/var/lib/vdr/aptosid-vdr/aptosid-vdr.conf"

# Localisation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=aptosid-vdr

VIDEO_DIR="/var/lib/video.00"

# stopping vdr for setup.conf handling
/etc/init.d/vdr stop

# Create conffiles for vdr that do not exist yet
CONFFILES="setup.conf remote.conf"
for CONF in $CONFFILES
  do
      if [ ! -e "/var/lib/vdr/$CONF" ] && [ -f "/var/lib/vdr/aptosid-vdr/$CONF" ]; then
          echo "copy /var/lib/vdr/aptosid-vdr/$CONF"
          cp -f "/var/lib/vdr/aptosid-vdr/$CONF" "/var/lib/vdr/$CONF"
          chown vdr:vdr "/var/lib/vdr/$CONF"
     fi
  done

if [ "$(grep ^LanguageMode $CONFIGFILE | cut -d= -f2)" -ne 1 ]; then
	# Set VDR-language automatically
	lang=$(grep ^OSDLanguage /var/lib/vdr/setup.conf | cut -d= -f2)
	[ "$lang" ] && old=$(echo $lang)
	[ -z "$lang" ] && old=0
	new=0 # default language, if detected language is not German
	[ "$(echo $LANG | cut -d\_ -f1)" = "de" ] && new=1
	
	if [ "$old" != "$new" ]; then
		if [ -z "$lang" ]; then
			echo "OSDLanguage = $new" >> /var/lib/vdr/setup.conf
		else
			perl -pi -e "s/^OSDLanguage =.*$/OSDLanguage = $new/" /var/lib/vdr/setup.conf
		fi
	fi
fi

# add xineliboutput. in setup.conf, needed for xineliboutput plugin
xlop=$(grep "xineliboutput" "/var/lib/vdr/setup.conf")
if [ "$xlop" = ""  ] ; then 
     echo "add xineliboutput preferences to /var/lib/vdr/setup.conf"
     grep "xineliboutput" "/var/lib/vdr/aptosid-vdr/setup.conf" >> "/var/lib/vdr/setup.conf"
     #sed -ie '/./!d' /var/lib/vdr/setup.conf
fi

# add xineliboutput. in setup.conf, needed for radio plugin
radio=$(grep "radio.Activate" "/var/lib/vdr/setup.conf")
if [ "$radio" = ""  ] ; then 
     echo "add radio.Activate preferences to /var/lib/vdr/setup.conf"
     echo "radio.Activate = 1" >> "/var/lib/vdr/setup.conf"
     #sed -ie '/./!d' /var/lib/vdr/setup.conf
fi

# add XkeySym. in remote.conf needed for vdr-sxfe
xkeysym=$(grep "XKeySym" "/var/lib/vdr/remote.conf")
if [ "$xkeysym" = ""  ] ; then 
     echo "add XKeySym Keys to /var/lib/vdr/remote.conf"
     cat "/var/lib/vdr/aptosid-vdr/remote.XKeySym.conf" >> "/var/lib/vdr/remote.conf"
     sed -ie '/./!d' /var/lib/vdr/remote.conf
fi

# is vdr enabled
enabled=$(grep "ENABLED" "/etc/default/vdr")
if [ "$enabled" ] ; then
   [ ! "$(echo $enabled | cut -d= -f2)" = "1" ] && sed -ie 's/ENABLED=.*$/ENABLED=1/' /etc/default/vdr
fi


# videodir test
videodir=$(grep "VIDEO_DIR" "/etc/default/vdr")
[ ! "$videodir" = "" ] && VIDEO_DIR="$(grep "VIDEO_DIR" "/etc/default/vdr" | cut -d\" -f2)" && \
    [ -L /var/lib/video ] && rm -f /var/lib/video
[ ! -d $VIDEO_DIR ] && mkdir $VIDEO_DIR && chown -R vdr:vdr $VIDEO_DIR && \
    [ -L /var/lib/video ] && rm -f /var/lib/video
[ ! -L /var/lib/video ] && ln -s $VIDEO_DIR /var/lib/video

# start vdr
/etc/init.d/vdr start
echo $"Please wait ..."
sleep 10

