#!/bin/sh

# Localisation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=sidux-vdr

DOWNLOAD="http://sidux.com/files/misc/"
WHAT=""

echo $"VDR Update Start"

cd "$HOME"
rm -f vdr-update.sh
wget "$DOWNLOAD/vdr-update.sh"
chmod 755 vdr-update.sh
chown root:root vdr-update.sh
sh vdr-update.sh $WHAT

echo
echo
echo " >>> "$"Update done"" <<<"

echo 
echo $"Press any key" && read

