#!/bin/sh

USERCONFIG="$HOME/.sidux-vdr.conf"

# Localisation
TEXTDOMAINDIR="/usr/share/locale"
TEXTDOMAIN=sidux-vdr


[ ! -e $HOME/vdrip.conf ] && /usr/sbin/vdr-ip
VDRIP=`head -1 $HOME/vdrip.conf`


# is vdr running
vdrrun="1" && vdrrun=`/etc/init.d/vdr status| grep -c not`
[ "$vdrrun" = "1" ] && [ $VDRIP = "localhost" -o $VDRIP = "127.0.0.1" ] && sleep 5  # wait for xine-autostart if kdestart is to fast
vdrrun="1" && vdrrun=`/etc/init.d/vdr status| grep -c not`
[ "$vdrrun" = "1" ] && [ $VDRIP = "localhost" -o $VDRIP = "127.0.0.1" ] && su-to-root -X -c "/usr/bin/x-terminal-emulator -e /usr/sbin/vdr-start"

runxine="0" && runxine=`ps -A|grep -c xine`
[ ! "$runxine" = "0" ] && /usr/sbin/vdr-xine-close 2>/dev/null
sleep 1

XineFullscreen=""
[ -f "$USERCONFIG" ] && [ "$(grep ^XineFullscreen $USERCONFIG | cut -d= -f2)" -eq 1 ] && XineFullscreen="-f"

NetworkTransportMode="tcp"
[ -f "$USERCONFIG" ] && [ "$(grep ^NetworkTransportMode $USERCONFIG | cut -d= -f2)" -eq 1 ] && NetworkTransportMode="udp"

#MRL="xvdr:${NetworkTransportMode}://$VDRIP"
MRL="xvdr://$VDRIP"  # NetworkTransportMode does not work
[ -f "$USERCONFIG" ] && [ "$(grep ^XinePlugin $USERCONFIG | cut -d= -f2)" -eq 1 ] && MRL="vdr-socket:/"$VDRIP"#demux:mpeg_pes"

if [ -z "$DISPLAY" ]; then
	fuser -k /dev/dsp &>/dev/null
	clear
	/usr/sbin/vdr-fbfe --post tvtime:method=Linear,cheap_mode=1,pulldown=0,use_progressive_frame_flag=1 "$MRL" &>/dev/null
	reset
else
	if [ "$1" = "sxfe" ] ; then
           [ ! -e /usr/bin/vdr-sxfe ] && \
               su-to-root -X -c "/usr/bin/x-terminal-emulator -e apt-get update; x-terminal-emulator -e apt-get install xineliboutput-sxfe"
               /usr/bin/vdr-sxfe ${XineFullscreen} --post tvtime:method=Linear,cheap_mode=1,pulldown=0,use_progressive_frame_flag=1 $MRL
        fi
	[ "$1" = "xine" -o "$1" = "" ] && xine ${XineFullscreen} -g -D --no-splash "$MRL#nocache;demux:mpeg_block" &
fi
