#!/bin/sh

# Localisation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=sidux-vdr

DIALOG=dialog

$DIALOG --title $"VDR Autostart" --yesno $"Shall VDR be started as default at boottime?" 0 0
	answer_autostart="$?"
	tput clear

if [ "$answer_autostart" = 0 ] ; then
	update-rc.d -f vdr remove
	update-rc.d vdr defaults 99
else
	update-rc.d -f vdr remove
fi

echo
echo $"Press any key" && read

