#!/bin/sh

USERCONFIG="$HOME/.sidux-vdr.conf"

# Localisation
TEXTDOMAINDIR="/usr/share/locale"
TEXTDOMAIN=sidux-vdr

DIALOG="dialog"
[ -n "$DISPLAY" ] && [ -x /usr/bin/Xdialog ] && DIALOG="Xdialog"

if [ ! -e $HOME/vdrip.conf ]; then
	VDRIP=`$DIALOG --inputbox $"VDR Server IP" 10 50 "localhost" 2>&1`
	if [ "$VDRIP" = "" ]; then
		exit;
	fi
	echo $VDRIP > $HOME/vdrip.conf
else
	VDRIP=`head -1 $HOME/vdrip.conf`
fi

# is vdr running
vdrrun="1" && vdrrun=`/etc/init.d/vdr status| grep -c not`
[ "$vdrrun" = "1" ] && [ $VDRIP = "localhost" -o $VDRIP = "127.0.0.1" ] && sleep 5  # wait for xine-autostart if kdestart is to fast
vdrrun="1" && vdrrun=`/etc/init.d/vdr status| grep -c not`
[ "$vdrrun" = "1" ] && [ $VDRIP = "localhost" -o $VDRIP = "127.0.0.1" ] && su-me x-terminal-emulator -e vdr-start

runxine="0" && runxine=`ps -A|grep -c xine`
[ ! "$runxine" = "0" ] && /usr/sbin/vdr-xine-close 2>/dev/null
sleep 1

XineFullscreen=""
[ -f "$USERCONFIG" ] && [ "$(grep ^XineFullscreen $USERCONFIG | cut -d= -f2)" -eq 1 ] && XineFullscreen="-f"

NetworkTransportMode="tcp"
[ -f "$USERCONFIG" ] && [ "$(grep ^NetworkTransportMode $USERCONFIG | cut -d= -f2)" -eq 1 ] && NetworkTransportMode="udp"

MRL="xvdr:${NetworkTransportMode}://$VDRIP"
[ -f "$USERCONFIG" ] && [ "$(grep ^XinePlugin $USERCONFIG | cut -d= -f2)" -eq 1 ] && MRL="vdr-socket:/"$VDRIP"#demux:mpeg_pes"

if [ -z "$DISPLAY" ]; then
	fuser -k /dev/dsp &>/dev/null
	clear
	vdr-fbfe --post tvtime:method=Linear,cheap_mode=1,pulldown=0,use_progressive_frame_flag=1 "$MRL" &>/dev/null
	reset
else
	[ "$1" = "sxfe" ] && vdr-sxfe ${XineFullscreen} --post tvtime:method=Linear,cheap_mode=1,pulldown=0,use_progressive_frame_flag=1 $MRL
	[ "$1" = "xine" -o "$1" = "" ] && xine ${XineFullscreen} -g -D --no-splash "$MRL#nocache;demux:mpeg_block" &
fi
