#!/bin/sh

# Localisation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=aptosid-vdr

# determine system status
SSFTSH="$(which ssft.sh)"			|| SSFTSH="/usr/bin/ssft.sh"

# initialize ssft
#[ -n "$DISPLAY" ] && [ -x /usr/bin/kdialog ] && SSFT_FRONTEND="kdialog"
. "$SSFTSH"
[ -n "$SSFT_FRONTEND" ] ||  SSFT_FRONTEND="$(ssft_choose_frontend)"


IP="localhost"
[ -e $HOME/vdrip.conf ] && IP=`head -1 $HOME/vdrip.conf`

SSFT_DEFAULT=${IP}
ssft_read_string "IP" $"VDR Server IP"  || exit 1
unset SSFT_DEFAULT

VDRIP=$SSFT_RESULT

if [ "$VDRIP" = "" ]; then
	exit 0;
fi
echo "$VDRIP" > "$HOME/vdrip.conf"
