#!/bin/sh

# Localisation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=aptosid-vdr

DIALOG=dialog

$DIALOG --title $"Xine Autostart" --yesno $"Shall Xine-Player (TV Picture) be started as default with KDE?" 0 0
	answer_autostart="$?"
	tput clear

if [ "$answer_autostart" = 0 ] ; then
	#cp /usr/sbin/vdr-xine $HOME/.kde/Autostart
	ln -s /usr/sbin/vdr-xine $HOME/.kde/Autostart
	echo
	echo $"Xine Autostart active!"
else
	rm -f $HOME/.kde/Autostart/vdr-xine
	echo
	echo $"Xine Autostart not active!"
fi

echo
echo $"Press any key" && read

