#!/bin/sh

# Localisation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=sidux-vdr

DOWNLOAD="http://sidux.com/files/misc/"
WHAT="libxine1 xine-ui"

DIALOG="dialog"
[ -n "$DISPLAY" ] && [ -x /usr/bin/Xdialog ] && DIALOG="Xdialog"

$DIALOG --title $"Installscript" --yesno \
$"When running this script, you need an active internet connection!\n\nProceed" 0 0
answer="$?"
[ "$answer" = 1 ] && exit 1
tput clear

echo $"VDR Update Start"

cd "$HOME"
rm -f vdr-update.sh
wget "$DOWNLOAD/vdr-update.sh"
chmod 755 vdr-update.sh
chown root:root vdr-update.sh
sh vdr-update.sh $WHAT

echo
echo
echo " >>> "$"Update done"" <<<"

echo 
echo $"Press any key" && read

