#!/bin/sh

# Localisation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=sidux-vdr


NOW=`date +%y-%m-%d_%H:%M:%S`

echo $"Plugin $1"
echo $"Please wait ..."

/usr/sbin/vdr-stop
BACKUPFILE="/var/backups/channels.conf.$NOW"
mv /var/lib/vdr/channels.conf "$BACKUPFILE"
touch /var/lib/vdr/channels.conf

w_pvrscan --plugin "$1" > /var/lib/vdr/channels.conf
chown vdr:vdr /var/lib/vdr/channels.conf

echo $"/var/lib/vdr/channels.conf done, Backup of existing channels.conf see $BACKUPFILE"

if [ -z "$DISPLAY" ]; then
	vdr-start
	TIMEOUT=""
else
	x-terminal-emulator -e vdr-start
	TIMEOUT=40000
fi
