#!/bin/sh

# Localisation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=kanotix-vdr

DIALOG="dialog"
[ -n "$DISPLAY" ] && [ -x /usr/bin/Xdialog ] && DIALOG="Xdialog"

TMP="/tmp/vdrip.tmp"

IP="localhost"
[ -e $HOME/vdrip.conf ] && IP=`head -1 $HOME/vdrip.conf`

$DIALOG --inputbox $"VDR Server IP" 10 50 "$IP" 2>"$TMP"
VDRIP="$(<$TMP)"
if [ "$VDRIP" = "" ]; then
	exit 0;
fi
echo "$VDRIP" > "$HOME/vdrip.conf"
