#!/bin/sh

. ssft.sh || exit 1

# Localisation
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=sidux-vdr

PFAD="/var/lib/vdr";

SSFT_FRONTEND="dialog"
[ -n "$DISPLAY" ] && SSFT_FRONTEND="zenity"

# Backup the channels.conf
NOW=`date +%y-%m-%d_%H:%M:%S`
BACKUPFILE="/var/backups/channels.conf.$NOW"
cp -f "$PFAD/channels.conf" "$BACKUPFILE"

# search the channel files
channellist=""
for i in $(ls $PFAD/channels.conf.* | cut -d. -f3-); do 
  channellist=$(echo "$channellist $i") 
done


if ssft_select_single "Channellist" $"Choose Channellist" $channellist; then
  cp -f "$PFAD/channels.conf.$SSFT_RESULT" "$PFAD/channels.conf"
else
  exit 0
fi

chown vdr:vdr $PFAD/channels.*

if [ "$DIALOG" = "dialog" ]; then
	vdr-start
else
	x-terminal-emulator -e vdr-start
fi

ssft_display_message "Info" $"Backup Channellist\n$BACKUPFILE"

